dubbo:
  application:
    name: sc_web
  registry:
    address: zookeeper://192.168.109.161:2181
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver